version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    hostname: elasticsearch
    environment: 
      - "discovery.type=single.node"
    ports:
      - 9201:9201
      - 9301:9301
    networks:
      - elknetwork
  kibana:
    image: kibana:7.9.3
    container_name: kibana
    hostname: kibana
    ports:
      - 5602:5602 
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  logstash:
    image: logstash:7.9.3
    container_name: logstash
    hostname: logstash    
    ports:
      - 9601:9601
      - 8089:8089
    volumes:
      - .\logstash:/usr/share/logstash/pipeline/
      - .\log:/var/log/
    links: 
      - elasticsearch:elasticsearch
    networks:
      - elknetwork
    depends_on:
      - elasticsearch
networks:
  elknetwork:
    driver: bridge